# Generated by Django 5.2.13 on 2026-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('is_escalated', models.BooleanField(default=False)),
                ('triage', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('runbook', models.TextField(blank=True)),
                ('qa_verdict', models.TextField(blank=True)),
                ('submitted_by', models.CharField(default='anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
